### ISSUE TITLE
Evaluation dataset release

### ISSUE THREAD

**Issue by 17Skye17** [ysy31415/direct_a_video#1]
Hi, thank you for releasing this excellent work.
I would like to know whether you will release the evaluation dataset (200 box-prompt pairs)?

**Comment by ysy31415** [comment]
Hi, thank you for your interest to our work. We can share the dataset later, currently i can't access to the server, please allow for some time, thanks.


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Skye ***@***.***>
发送时间: Thursday, June 20, 2024 10:36:32 AM
收件人: ysy31415/direct_a_video ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Ext] [ysy31415/direct_a_video] Evaluation dataset release (Issue #1)

CAUTION: External email. Do not reply, click on links or open attachments unless you recognize the sender and know the content is safe.


Hi, thank you for releasing this excellent work.
I would like to know whether you will release the evaluation dataset (200 box-prompt pairs)?

―

**Comment by 17Skye17** [comment]
Hi, thank you for your reply. May I know about the estimated release time? : )

**Comment by ysy31415** [comment]
Hi, maybe 3-4 days I guess, I am on vacation leave right now 😊

**Comment by 17Skye17** [comment]
Hi, sorry to bother again. If you have time, could you send me the download links to the evaluation dataset? Thank you.

**Comment by ysy31415** [comment]
Hi, sorry for the late reply, you can find it via this link:

https://portland-my.sharepoint.com/:f:/g/personal/shiyyang8-c_my_cityu_edu_hk/EuGljGuN_1lJnPArm9kOwbUBbUe80KQw7k04ZmFRsMmU9w?e=Q1aaJ2

**Comment by 17Skye17** [comment]
Thank you for sharing! : )
